package com.github.rodrigopr.scared.mapping

import com.github.rodrigopr.scared.annotations.Id

class Field(field: java.lang.reflect.Field) {

  field.setAccessible(true)
  private val idAnnotation = Option(field.getAnnotation(classOf[Id]))

  val name = field.getName
  var isId = idAnnotation.isDefined
  val isAutoGenerated = idAnnotation.map(id => id.autoGenerated()).getOrElse(false)

  val fieldType = field.getType
  val isCollection = classOf[List[_]].isAssignableFrom(field.getType)
}
