package com.github.rodrigopr.scared.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface Id {
  boolean autoGenerated() default true;
}
